# baseURL
@baseURL = http://localhost:5000/api

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "firstName": "String",
    "lastName": "String",
    "email": "example@email.com",
    "gender": "Male||Female"
    "birthday": "MM/DD/YYYY"
    "address": "String",
    "contactNumber": "String"
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
