import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const LoginPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>LoginPage</title>
        {/* <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="h-screen w-full bg-green-100">
        <div className="flex min-h-full justify-center py-12 px-4 sm:px-6 lg:px-8">
          <div className="w-full min-w-fit min-h-fit space-y-10 max-w-xl bg-white flex flex-col justify-center py-10 rounded-xl drop-shadow-2xl">
            <Link href="/">
              <div className="flex flex-row mx-2 self-center items-center text-center cursor-pointer select-none hover:bg-green-50 hover:text-green-900 max-w-fit p-2 rounded-md">
                <img className="w-24 mr-5" src="/logo.svg" alt="logo" />
                <div className="flex flex-col  ">
                  <h1 className="text-2xl">Medidas Medical Center</h1>
                  <h3 className="text-lg">Valencia City, Bukidnon</h3>
                </div>
              </div>
            </Link>
            <h1 className="text-4xl font-bold text-center">
              Sign in your Account
            </h1>
            <form className="yt-8 space-y-6 w-96 m-10 self-center">
              <div>
                <label className="block text-sm font-medium text-grey-700">
                  Email
                </label>
                <div className="relative mt-1 rounded-md shadow-sm ">
                  <input
                    type="email"
                    name="email"
                    id="email"
                    className="block w-full h-10 rounded-md border  border-green-300 pl-3 pr-12 focus:border-green-500 focus:ring-4 focus:ring-green-200 sm:text-sm"
                    placeholder="john.doe@example.com"
                    required
                  />
                </div>
              </div>
              <div>
                <button
                  type="submit"
                  className="group relative flex w-full justify-center rounded-md border border-transparent bg-green-600 py-2 px-4 text-lg font-semibold text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
                >
                  Sign in
                </button>
              </div>
              <div className="bg-green-50 py-2 px-5 rounded-md text-center">
                <span className=" text-gray-700 text-md">
                  We’ll email you a magic code for a
                </span>
                <br />
                <span className=" text-gray-700 text-md ">
                  password-free sign in.
                </span>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default LoginPage;
